apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: card-transaction-schema
  description: Reusable schema for CardTransaction object
spec:
  type: schema
  schema:
    type: object
    properties:
        BeneficiaryEntry:
            type: object
            properties:
                referenceId:
                    type: string
        StatusInstanceRecord:
            $ref: 'https://raw.githubusercontent.com/LuisCeballos24/api-backstage/c06b5e72f16ca6ee9932b654a977f5a47a90a5f3/commons/Objects/StatusInstanceRecord.yaml'
