openapi: 3.0.3
info:
  title: Cash Management And Account Services
  description: Cash Management And Account Services
  version: 3.0.0
servers:
  - url: 'https://test.api.ob.banesco.com.pa/system/TradeBanking/CashManagementAndAccountServices/3.0.0/'
paths:
  /v3/DepositsandWithdrawals/Execute:
    put:
      tags:
        - DepositsandWithdrawals
      summary: Execute DepositsandWithdrawals
      description: Operación asociada al área de Account que permite depositar efectivo.
      operationId: ExecuteDepositsandWithdrawals
      parameters:
        - $ref: '#/components/parameters/ClientDt'
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/ClientApp-ChannelId'
        - $ref: '#/components/parameters/ClientApp-Name'
        - $ref: '#/components/parameters/ClientApp-UserId'
        - $ref: '#/components/parameters/X-API-Key'

      requestBody:
        $ref: '#/components/requestBodies/ExecuteDepositsandWithdrawalsRq'

      responses:
       '200':
          $ref: '#/components/responses/ExecuteDepositsandWithdrawalsRs'
       '400':
          $ref: '#/components/responses/badRequest'
       '401':
          $ref: '#/components/responses/unauthorized'
       '403':
          $ref: '#/components/responses/forbidden'
       '404':
          $ref: '#/components/responses/notFound'
       '408':
          $ref: '#/components/responses/timeOut'
       '500':
          $ref: '#/components/responses/internalServerError'


components:
  parameters:
    ### Headers ###
    ClientDt:
      name: ClientDt
      in: header
      schema:
        type: string
      required: true
    RequestId:
      name: RequestId
      in: header
      schema:
        type: string
      required: true
    ClientApp-ChannelId:
      name: ClientApp-ChannelId
      in: header
      schema:
        type: string
      required: true
    ClientApp-Name:
      name: ClientApp-Name
      in: header
      schema:
        type: string
      required: true
    ClientApp-UserId:
      name: ClientApp-UserId
      in: header
      schema:
        type: string
      required: true
    X-API-Key:
      name: X-API-Key
      in: header
      schema:
        type: string
      required: true
    ### Headers ###

  schemas:
    ### Request ###
    ExecuteDepositsandWithdrawalsRq:
      $ref: './Operations/ExecuteDepositsandWithdrawals/ExecuteDepositsandWithdrawalsRq.yaml'
    ### Request ###

    ### Response ###
    ExecuteDepositsandWithdrawalsRs:
      $ref: './Operations/ExecuteDepositsandWithdrawals/ExecuteDepositsandWithdrawalsRs.yaml'
    ### Http Response ###
    httpResponse:
      $ref: '../../commons/HttpResponses/HttpError.yaml'
    ### Http Response ###

    ### Response ###


  ### Define Relation with  Request ###
  requestBodies:
    ### Artefacts Request ###
    ExecuteDepositsandWithdrawalsRq:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecuteDepositsandWithdrawalsRq'
          example:
            AccountReference:
              AccountIdentification:
              - Identifier:
                  identifierValue: ""
            PartyReference:
              User:
                userName: ""
            TransactionFacility:
              Amount:
                amount: 1234
                currencyCode: ""
              agencyName: ""
            
    
    ### Artefacts Request ###
  ### Define Relation with  Request ###



  ### Define Relation with  Response ###
  responses:
    ### Artefacts Response ###
    ExecuteDepositsandWithdrawalsRs:
      description: ExecuteDepositsandWithdrawalsRs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecuteDepositsandWithdrawalsRs'
          example:
            TransactionFacility:
              referenceNumber: ""
              transactionDate: ""
            
    
    ### Artefacts Responses ###

    ### Https Responses ###
    badRequest:
      description: badRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Bad Request"
            status: "FAILED"
            statusCode: "400"
            
    
    unauthorized:
      description: unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Unauthorized"
            status: "FAILED"
            statusCode: "401"
            
    
    forbidden:
      description: forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Forbidden"
            status: "FAILED"
            statusCode: "403"
            
    
    notFound:
      description: notFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Not Found"
            status: "FAILED"
            statusCode: "404"
            
    
    timeOut:
      description: timeOut
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Time Out"
            status: "FAILED"
            statusCode: "408"
            
    
    internalServerError:
      description: internalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Internal Server Error"
            status: "FAILED"
            statusCode: "500"
            
    
    ### Https Responses ###
  ### Define Relation with  Response ###

