openapi: 3.0.3
info:
  title: Servicing Mandate
  description: Servicing Mandate
  version: 3.0.0
servers:
  - url: 'https://test.api.ob.banesco.com.pa/experience/Servicing/ServicingMandate/3.0.0/'
paths:
  /v3/ServicingMandateEntry/Register:
    post:
      tags:
        - ServicingMandateEntry
      summary: Register ServicingMandateEntry
      description: Servicio de Recepci贸n encargada de registrar condiciones de movilizaci贸n de firmantes.
      operationId: RegisterServicingMandateEntry
      parameters:
        - $ref: '#/components/parameters/ClientDt'
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/ClientApp-ChannelId'
        - $ref: '#/components/parameters/ClientApp-Name'
        - $ref: '#/components/parameters/ClientApp-UserId'
        - $ref: '#/components/parameters/X-API-Key'

      requestBody:
        $ref: '#/components/requestBodies/RegisterServicingMandateEntryRq'

      responses:
       '200':
          $ref: '#/components/responses/RegisterServicingMandateEntryRs'
       '400':
          $ref: '#/components/responses/badRequest'
       '401':
          $ref: '#/components/responses/unauthorized'
       '403':
          $ref: '#/components/responses/forbidden'
       '404':
          $ref: '#/components/responses/notFound'
       '408':
          $ref: '#/components/responses/timeOut'
       '500':
          $ref: '#/components/responses/internalServerError'


  /v3/ServicingMandateEntry/Update:
    patch:
      tags:
        - ServicingMandateEntry
      summary: Update ServicingMandateEntry
      description: Servicio de Recepci贸n encargada de registrar condiciones de movilizaci贸n de firmantes.
      operationId: UpdateServicingMandateEntry
      parameters:
        - $ref: '#/components/parameters/ClientDt'
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/ClientApp-ChannelId'
        - $ref: '#/components/parameters/ClientApp-Name'
        - $ref: '#/components/parameters/ClientApp-UserId'
        - $ref: '#/components/parameters/X-API-Key'

      requestBody:
        $ref: '#/components/requestBodies/UpdateServicingMandateEntryRq'

      responses:
       '200':
          $ref: '#/components/responses/UpdateServicingMandateEntryRs'
       '400':
          $ref: '#/components/responses/badRequest'
       '401':
          $ref: '#/components/responses/unauthorized'
       '403':
          $ref: '#/components/responses/forbidden'
       '404':
          $ref: '#/components/responses/notFound'
       '408':
          $ref: '#/components/responses/timeOut'
       '500':
          $ref: '#/components/responses/internalServerError'


components:
  parameters:
    ### Headers ###
    ClientDt:
      name: ClientDt
      in: header
      schema:
        type: string
      required: true
    RequestId:
      name: RequestId
      in: header
      schema:
        type: string
      required: true
    ClientApp-ChannelId:
      name: ClientApp-ChannelId
      in: header
      schema:
        type: string
      required: true
    ClientApp-Name:
      name: ClientApp-Name
      in: header
      schema:
        type: string
      required: true
    ClientApp-UserId:
      name: ClientApp-UserId
      in: header
      schema:
        type: string
      required: true
    X-API-Key:
      name: X-API-Key
      in: header
      schema:
        type: string
      required: true
    ### Headers ###

  schemas:
    ### Request ###
    RegisterServicingMandateEntryRq:
      $ref: './Operations/RegisterServicingMandateEntry/RegisterServicingMandateEntryRq.yaml'
    UpdateServicingMandateEntryRq:
      $ref: './Operations/UpdateServicingMandateEntry/UpdateServicingMandateEntryRq.yaml'
    ### Request ###

    ### Response ###
    RegisterServicingMandateEntryRs:
      $ref: './Operations/RegisterServicingMandateEntry/RegisterServicingMandateEntryRs.yaml'
    UpdateServicingMandateEntryRs:
      $ref: './Operations/UpdateServicingMandateEntry/UpdateServicingMandateEntryRs.yaml'
    ### Http Response ###
    httpResponse:
      $ref: '../../commons/HttpResponses/HttpError.yaml'
    ### Http Response ###

    ### Response ###


  ### Define Relation with  Request ###
  requestBodies:
    ### Artefacts Request ###
    RegisterServicingMandateEntryRq:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RegisterServicingMandateEntryRq'
          example:
            ServicingMandateEntry:
              Agreement:
              - SignatoryGroup:
                - PartyReference:
                    Person:
                      PersonName:
                      - personName: ""
                  groupId: ""
                agreement: ""
                agreementAmount: 20.5
                signatoriesMinAmount: 5
              Identifier:
                identifierValue: ""
              currency: ""
              description: ""
            
    
    UpdateServicingMandateEntryRq:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateServicingMandateEntryRq'
          example:
            ServicingMandateEntry:
              Agreement:
              - SignatoryGroup:
                - PartyReference:
                    Person:
                      PersonName:
                      - personName: ""
                  groupId: ""
                agreement: ""
                agreementAmount: 20.5
                signatoriesMinAmount: 5
              Identifier:
                identifierValue: ""
              currency: ""
              description: ""
            
    
    ### Artefacts Request ###
  ### Define Relation with  Request ###



  ### Define Relation with  Response ###
  responses:
    ### Artefacts Response ###
    RegisterServicingMandateEntryRs:
      description: RegisterServicingMandateEntryRs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RegisterServicingMandateEntryRs'
          example:
            ServicingMandateEntry:
              Identifier:
                identifierValue: ""
              description: ""
            
    
    UpdateServicingMandateEntryRs:
      description: UpdateServicingMandateEntryRs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateServicingMandateEntryRs'
          example:
            ServicingMandateEntry:
              Identifier:
                identifierValue: ""
              description: ""
            
    
    ### Artefacts Responses ###

    ### Https Responses ###
    badRequest:
      description: badRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Bad Request"
            status: "FAILED"
            statusCode: "400"
            
    
    unauthorized:
      description: unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Unauthorized"
            status: "FAILED"
            statusCode: "401"
            
    
    forbidden:
      description: forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Forbidden"
            status: "FAILED"
            statusCode: "403"
            
    
    notFound:
      description: notFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Not Found"
            status: "FAILED"
            statusCode: "404"
            
    
    timeOut:
      description: timeOut
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Time Out"
            status: "FAILED"
            statusCode: "408"
            
    
    internalServerError:
      description: internalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Internal Server Error"
            status: "FAILED"
            statusCode: "500"
            
    
    ### Https Responses ###
  ### Define Relation with  Response ###

