apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: UpdateBeneficiaryEntryRs
  links:
    - url: https://github.com/LuisCeballos24/api-backstage
      title: Source Code
      icon: github
    - url: https://test.api.ob.banesco.com.pa
      title: Production
      icon: globe
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: https://github.com/LuisCeballos24/api-backstage/blob/main/Proxy/CashManagementAndAccountServices/CashManagementAndAccountServices.yaml
spec:
  type: openapi
  lifecycle: production
  owner: user:LuisCeballos24
  system: cash-management
  dependsOn: ['resource:heroes-db']
  apiConsumedBy: ['component:www-heroes']
  definition: |
    type: object
    properties:
        BeneficiaryEntry:
            type: object
            properties:
                referenceId:
                    type: string
        StatusInstanceRecord:
            $ref: '../../../../commons/Objects/StatusInstanceRecord.yaml'
