apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: UpdateBeneficiaryEntryRs
  description: Reusable schema for CardTransaction object
spec:
  type: schema
  schema:
    type: object
    properties:
        BeneficiaryEntry:
            type: object
            properties:
                referenceId:
                    type: string
        StatusInstanceRecord:
            $ref: '../../../../commons/Objects/StatusInstanceRecord.yaml'
