apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: UpdateBeneficiaryEntryRq
  description: Reusable schema for CardTransaction object
spec:
  type: schema
  schema:
    type: object
    properties:
        BeneficiaryEntry:
            $ref: 'https://raw.githubusercontent.com/LuisCeballos24/api-backstage/blob/cf01bfd87036d52a724713f556808f5edc86116f/commons/Objects/BeneficiaryEntry.yaml'
