openapi: 3.0.3
info:
  title: Payment Instruction
  description: Payment Instruction
  version: 3.0.0
servers:
  - url: 'https://test.api.ob.banesco.com.pa/experience/Payments/PaymentInstruction/3.0.0/'
paths:
  /v3/PaymentInstructionProcedure/Exchange:
    put:
      tags:
        - PaymentInstructionProcedure
      summary: Exchange PaymentInstructionProcedure
      description: Operación encargada de insertar los datos de un beneficiario de tarjeta de crédito.
      operationId: ExchangePaymentInstructionProcedure
      parameters:
        - $ref: '#/components/parameters/ClientDt'
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/ClientApp-ChannelId'
        - $ref: '#/components/parameters/ClientApp-Name'
        - $ref: '#/components/parameters/ClientApp-UserId'
        - $ref: '#/components/parameters/X-API-Key'

      requestBody:
        $ref: '#/components/requestBodies/ExchangePaymentInstructionProcedureRq'

      responses:
       '204':
          description: 'Not content'
       '400':
          $ref: '#/components/responses/badRequest'
       '401':
          $ref: '#/components/responses/unauthorized'
       '403':
          $ref: '#/components/responses/forbidden'
       '404':
          $ref: '#/components/responses/notFound'
       '408':
          $ref: '#/components/responses/timeOut'
       '500':
          $ref: '#/components/responses/internalServerError'


  /v3/SwiftPaymentsProcedure/Create:
    post:
      tags:
        - SwiftPaymentsProcedure
      summary: Create SwiftPaymentsProcedure
      description: Crear Afiliación de Cobro por Servicio MT940 SWIFT
      operationId: CreateSwiftPaymentsProcedure
      parameters:
        - $ref: '#/components/parameters/ClientDt'
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/ClientApp-ChannelId'
        - $ref: '#/components/parameters/ClientApp-Name'
        - $ref: '#/components/parameters/ClientApp-UserId'
        - $ref: '#/components/parameters/X-API-Key'

      requestBody:
        $ref: '#/components/requestBodies/CreateSwiftPaymentsProcedureRq'

      responses:
       '200':
          $ref: '#/components/responses/CreateSwiftPaymentsProcedureRs'
       '400':
          $ref: '#/components/responses/badRequest'
       '401':
          $ref: '#/components/responses/unauthorized'
       '403':
          $ref: '#/components/responses/forbidden'
       '404':
          $ref: '#/components/responses/notFound'
       '408':
          $ref: '#/components/responses/timeOut'
       '500':
          $ref: '#/components/responses/internalServerError'


  /v3/SwiftPaymentsProcedure/Update:
    patch:
      tags:
        - SwiftPaymentsProcedure
      summary: Update SwiftPaymentsProcedure
      description: Actualizar Afiliación de Cobro por Servicio MT940 SWIFT
      operationId: UpdateSwiftPaymentsProcedure
      parameters:
        - $ref: '#/components/parameters/ClientDt'
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/ClientApp-ChannelId'
        - $ref: '#/components/parameters/ClientApp-Name'
        - $ref: '#/components/parameters/ClientApp-UserId'
        - $ref: '#/components/parameters/X-API-Key'

      requestBody:
        $ref: '#/components/requestBodies/UpdateSwiftPaymentsProcedureRq'

      responses:
       '200':
          $ref: '#/components/responses/UpdateSwiftPaymentsProcedureRs'
       '400':
          $ref: '#/components/responses/badRequest'
       '401':
          $ref: '#/components/responses/unauthorized'
       '403':
          $ref: '#/components/responses/forbidden'
       '404':
          $ref: '#/components/responses/notFound'
       '408':
          $ref: '#/components/responses/timeOut'
       '500':
          $ref: '#/components/responses/internalServerError'


components:
  parameters:
    ### Headers ###
    ClientDt:
      name: ClientDt
      in: header
      schema:
        type: string
      required: true
    RequestId:
      name: RequestId
      in: header
      schema:
        type: string
      required: true
    ClientApp-ChannelId:
      name: ClientApp-ChannelId
      in: header
      schema:
        type: string
      required: true
    ClientApp-Name:
      name: ClientApp-Name
      in: header
      schema:
        type: string
      required: true
    ClientApp-UserId:
      name: ClientApp-UserId
      in: header
      schema:
        type: string
      required: true
    X-API-Key:
      name: X-API-Key
      in: header
      schema:
        type: string
      required: true
    ### Headers ###

  schemas:
    ### Request ###
    ExchangePaymentInstructionProcedureRq:
      $ref: './Operations/ExchangePaymentInstructionProcedure/ExchangePaymentInstructionProcedureRq.yaml'
    CreateSwiftPaymentsProcedureRq:
      $ref: './Operations/CreateSwiftPaymentsProcedure/CreateSwiftPaymentsProcedureRq.yaml'
    UpdateSwiftPaymentsProcedureRq:
      $ref: './Operations/UpdateSwiftPaymentsProcedure/UpdateSwiftPaymentsProcedureRq.yaml'
    ### Request ###

    ### Response ###
    CreateSwiftPaymentsProcedureRs:
      $ref: './Operations/CreateSwiftPaymentsProcedure/CreateSwiftPaymentsProcedureRs.yaml'
    UpdateSwiftPaymentsProcedureRs:
      $ref: './Operations/UpdateSwiftPaymentsProcedure/UpdateSwiftPaymentsProcedureRs.yaml'
    ### Http Response ###
    httpResponse:
      $ref: '../../commons/HttpResponses/HttpError.yaml'
    ### Http Response ###

    ### Response ###


  ### Define Relation with  Request ###
  requestBodies:
    ### Artefacts Request ###
    ExchangePaymentInstructionProcedureRq:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExchangePaymentInstructionProcedureRq'
          example:
            PaymentInstructionProcedure:
              paymentInstructionType: ""
            TransactionFacility:
              referenceId: ""
            
    
    CreateSwiftPaymentsProcedureRq:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateSwiftPaymentsProcedureRq'
          example:
            SwiftPayments:
              Amount:
                amountValue: 1234
              PayeeProductReference:
                AccountReference:
                  AccountFacility:
                    AccountDetails:
                      Category:
                        code: ""
              PayerProductReference:
                AccountReference:
                  AccountFacility:
                    AccountDetails:
                      Category:
                        code: ""
                  AccountIdentification:
                  - Identifier:
                      identifierValue: ""
                  referenceId: ""
              TransactionReference:
                FinancialTransaction:
                - financialTransactionFrequency: ""
              category: ""
              status: ""
            
    
    UpdateSwiftPaymentsProcedureRq:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateSwiftPaymentsProcedureRq'
          example:
            SwiftPayments:
              Amount:
                amountValue: 1234
              PayeeProductReference:
                AccountReference:
                  AccountFacility:
                    AccountDetails:
                      Category:
                        code: ""
              PayerProductReference:
                AccountReference:
                  AccountFacility:
                    AccountDetails:
                      Category:
                        code: ""
                  AccountIdentification:
                  - Identifier:
                      identifierValue: ""
                  referenceId: ""
              TransactionReference:
                FinancialTransaction:
                - financialTransactionFrequency: ""
              category: ""
              status: ""
            
    
    ### Artefacts Request ###
  ### Define Relation with  Request ###



  ### Define Relation with  Response ###
  responses:
    ### Artefacts Response ###
    CreateSwiftPaymentsProcedureRs:
      description: CreateSwiftPaymentsProcedureRs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateSwiftPaymentsProcedureRs'
          example:
            SwiftPayments:
              PayerProductReference:
                AccountReference:
                  referenceId: ""
              transactionDate: ""
            
    
    UpdateSwiftPaymentsProcedureRs:
      description: UpdateSwiftPaymentsProcedureRs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateSwiftPaymentsProcedureRs'
          example:
            SwiftPayments:
              PayerProductReference:
                AccountReference:
                  referenceId: ""
              transactionDate: ""
            
    
    ### Artefacts Responses ###

    ### Https Responses ###
    badRequest:
      description: badRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Bad Request"
            status: "FAILED"
            statusCode: "400"
            
    
    unauthorized:
      description: unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Unauthorized"
            status: "FAILED"
            statusCode: "401"
            
    
    forbidden:
      description: forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Forbidden"
            status: "FAILED"
            statusCode: "403"
            
    
    notFound:
      description: notFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Not Found"
            status: "FAILED"
            statusCode: "404"
            
    
    timeOut:
      description: timeOut
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Time Out"
            status: "FAILED"
            statusCode: "408"
            
    
    internalServerError:
      description: internalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Internal Server Error"
            status: "FAILED"
            statusCode: "500"
            
    
    ### Https Responses ###
  ### Define Relation with  Response ###

